name:                hq
version:             0.1.0.0
github:              "github.com/ghais/hq"
license:             BSD3
author:              "Ghais"
maintainer:          "0x47@0x49.dev"
copyright:           "2020 Ghais Issa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Quantitative Library
#category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ghais/hq#readme>

dependencies:
- base >= 4.7 && < 5
- cassava
- vector
- containers
- random
- mersenne-random-pure64
- rvar
- random-source
- random-fu
- hmatrix
- statistics
- bytestring
- cassava
- time
- conversion
- sorted-list
- random-fu-multivariate
- Chart
- Chart-diagrams
- hmatrix-gsl
- transformers
- mtl
- text
- ad
- monad-loops
- hvega
- gnuplot
- math-functions
- ieee754
- erf
- hspec
- hspec-expectations
- data-default-class
- criterion

library:
  source-dirs: src
  cxx-sources:
        - external/src/lets_be_rational.cpp
        - external/src/normaldistribution.cpp
        - external/src/rationalcubic.cpp
        - external/src/erf_cody.cpp
  include-dirs:
        - external/include
        - external/src

executables:
  test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hq

tests:
  bachelier:
    main:                Spec.hs
    source-dirs:         test/bachelier
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [hq]
  normalimpliedvol:
    main:                Spec.hs
    source-dirs:         test/normalimpliedvol
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [hq]
